### ISSUE TITLE
Exception on transform inside renderIcon()

### ISSUE THREAD

**Issue by fabriziomoscon** [djchie/react-native-star-rating#56]
config:
```
"react-native": "0.47.2"
"react-native-star-rating": "^1.0.8"
Android 7.1.0 real device
```

my code
```
<StarRating
  disabled={false}
  maxStars={5}
  rating={this.state.rating}
  selectedStar={rating => this.setState({ rating })}
  starStyle={{paddingHorizontal: 6}}
  starSize={50}
  starColor={colors.active}
  emptyStarColor={colors.active}
  emptyStar="star-border"
  iconSet="MaterialIcons"
/>
```

Error stack:
```
TypeError: Cannot create property 'transform' on number '351'
    at update (index.js:157)
    at StarButton.renderIcon (star-button.js:76)
    at StarButton.render (star-button.js:131)
    at ReactNativeStack-dev.js:1863
    at measureLifeCyclePerf (ReactNativeStack-dev.js:1610)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactNativeStack-dev.js:1862)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactNativeStack-dev.js:1872)
    at ReactCompositeComponentWrapper.performInitialMount (ReactNativeStack-dev.js:1696)
    at ReactCompositeComponentWrapper.mountComponent (ReactNativeStack-dev.js:1655)
    at Object.mountComponent (ReactNativeStack-dev.js:1327)
```

UPDATE
@djchie  If I remove `starStyle` everything works, so I think the code expects a style structured in a particular way.

**Comment by FredericRuaudel** [comment]
I'm also having a problem with the `starStyle`.

It appears in version 1.0.8 since it works well in 1.0.7 for me. 

After some investigation, it seems to comes from the code below:

https://github.com/djchie/react-native-star-rating/blob/29ddc586dc79e67b2539e2bad8106a5af1db1f98/star-button.js#L76-L84

However, what is strange, is that when I setup style inline like you did: 

`starStyle={{paddingHorizontal: 6}}`

It works perfectly, but when I use a style from a StyleSheet object, like:

`starStyle={{styles.star}}`

I got a:

`TypeError: Attempted to assign to readonly property` 

in a red screen and the stack you mentioned in the debugger:

`Cannot create property 'transform' on number 'XXX'`

Which makes sense since `StyleSheet` references are kind of ids (the number 'XXX')

We can probably fix this issue by applying [`StyleSheet.flatten()`](https://facebook.github.io/react-native/docs/stylesheet.html#flatten) on the style before updating it. 🤔

**Comment by djchie** [comment]
Thanks for the catch @fabriziomoscon and thanks for the fix @FredericRuaudel!
